### PR TITLE
simplify threejs imports

### PR DESCRIPTION
**Pull request by ChristopherChudzicki**
This PR simplifies the "three" imports as discussed in #49.

**Do not merge:** Until Threestrap v0.5.1 is published. *Oh, the CI tests should fail until then anyway*.

### CODE REVIEW

**Comment by sritchie** [comment]
Great work, I'll get all these reviewed and merged this morning. It was really nice to see the bundle size improvements!

**Comment by sritchie** [comment]
As you say, it looks like the failures come from no threestrap 0.5.1 yet. I'm excited to get publishing automated here...

Thanks for undoing my unintentionally-destructive work here!!

**Comment by sritchie** [comment]
(Merge away when threestrap's published)

**Comment by ChristopherChudzicki** [comment]
@sritchie Thanks for the reviews! PR for the `instanceof` of change will be a bit later today, I hope.

**Pull request merged**
